apiVersion: v1
kind: Service
metadata:
  name: gateway-local
  namespace: default
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: buscacep-api-local
  namespace: default
spec:
  type: NodePort
  selector:
    app: buscacep-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30000
