apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    aiops.platform/domain: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    aiops.platform/domain: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    aiops.platform/domain: infra
